
 const translationsEn = {
    home : "Home",
    about : "About",
    search : "Search...",
    createlisting : "Create a Listing",
    imagecover: "The first image will be cover (max 6)",
    images: "Images",
    creating : "Creating...",
    upload : "Upload",
    uploading: "Uploading...",
    imageserror1: "Image upload failed (2 mb max per image)",
    imageserror2: "You can only upload 6 images per listing",
    imageserror3: "You must upload at least one image",
    imageserror4: "Error Image upload(image must be less than 2 mb)",
    discounterror1: "Discountprice must be lower than regular price",
    name : "Name",
    description : "Description",
    address : "Address",
    sell: "Sell",
    rent: "Rent",
    parking: "Parking spot",
    furnished : "Furnished",
    offer : "Offer",
    beds : "Beds",
    baths : "Baths",
    regularprice : "Regular price",
    $month : "$ / month",
    discountPrice : "DiscountPrice" ,
    profile : "Profile",
    uploadSuccess: "Image seccessfully uploaded!",
    username:"username",
    email:"email",
    password: "password",
    update: "Update",
    loading: "Loading" ,
    delete_account : "Delete account",
    sign_out : "Sign Out",
    userUpdateSuccess : "User is updated successfully!",
    unauthorized : "Unauthorized",
    forbidden : "Forbidden",

}

export default translationsEn;
