const translationsUz = {
    home : "Uy",
    about : "Haqida",
    search : "Qidiruv...",
    createlisting : "Ro'yxat yaratish",
    imagecover: "Birinchi rasm qopqoq bo'ladi (maksimal 6)",
    images: "Tasvirlar",
    creating : "Yaratilmoqda...",
    upload : "Yuklash",
    uploading: "Yuklanmoqda...",
    imageserror1: "Rasm yuklanmadi (har bir rasm uchun maksimal 2 mb)",
    imageserror2: "Har bir ro'yxatda faqat 6 ta rasm yuklashingiz mumkin",
    imageserror3: "Kamida bitta rasm yuklashingiz kerak",
    imageserror4: "Rasmni yuklashda xatolik (rasm 2 mb dan kam boʻlishi kerak)",
    discounterror1: "Chegirma odatdagi narxdan past bo'lishi kerak",
    name : "Nomi",
    description : "Tavsif",
    address : "Manzil",
    sell: "Sotish",
    rent: "Ijara",
    parking: "Avto Turargoh",
    furnished : "Mebel bilan jihozlangan",
    offer : "Taklif",
    beds : "Yotoqxona",
    baths : "Vannalar",
    regularprice : "Muntazam narx",
    $month : "$ / oy",
    discountPrice : "Chegirma narx",
    profile : "Profil",
    uploadSuccess : "Rasm xavfsiz yuklandi!",
    username:"foydalanuvchi nomi",
    email:"elektron pochta",
    password: "parol",
    update : "Yangilash",
    loading: "Yuklanmoqda",
    delete_account : "Hisobni o'chirish",
    sign_in : "Kirish",
    sign_out : "Tizimdan chiqish",
    userUpdateSuccess : "Foydalanuvchi muvaffaqiyatli yangilandi!",
    unauthorized : "Ruxsatsiz!",
    forbidden : "Taqiqlangan",
    password : "Parol",
    continue_to_google : "Google orqali davom ettirish",
    sign_up : "Ro'yxatdan o'tish",
    dont_have_account : "Hisobingiz yo'qmi ?",
    have_an_account : "Hisobingiz bormi ?",
    


}

export default translationsUz;